export enum SvgIcons {
  Trash = 'trash',
  SettingsGear = 'settings-gear',
  Send = 'send',
  Undo = 'undo',
  Chess = 'chess',

  AlphaWR = 'alpha-wr',
  AlphaWQ = 'alpha-wq',
  AlphaWP = 'alpha-wp',
  AlphaWN = 'alpha-wn',
  AlphaWK = 'alpha-wk',
  AlphaWB = 'alpha-wb',
  AlphaBR = 'alpha-br',
  AlphaBQ = 'alpha-bq',
  AlphaBP = 'alpha-bp',
  AlphaBN = 'alpha-bn',
  AlphaBK = 'alpha-bk',
  AlphaBB = 'alpha-bb',

  LeipzigWR = 'leipzig-wr',
  LeipzigWQ = 'leipzig-wq',
  LeipzigWP = 'leipzig-wp',
  LeipzigWN = 'leipzig-wn',
  LeipzigWK = 'leipzig-wk',
  LeipzigWB = 'leipzig-wb',
  LeipzigBR = 'leipzig-br',
  LeipzigBQ = 'leipzig-bq',
  LeipzigBP = 'leipzig-bp',
  LeipzigBN = 'leipzig-bn',
  LeipzigBK = 'leipzig-bk',
  LeipzigBB = 'leipzig-bb',

  MayaWR = 'maya-wr',
  MayaWQ = 'maya-wq',
  MayaWP = 'maya-wp',
  MayaWN = 'maya-wn',
  MayaWK = 'maya-wk',
  MayaWB = 'maya-wb',
  MayaBR = 'maya-br',
  MayaBQ = 'maya-bq',
  MayaBP = 'maya-bp',
  MayaBN = 'maya-bn',
  MayaBK = 'maya-bk',
  MayaBB = 'maya-bb',
}
